[config]
schemaVersion = "0.0.1"

[package]
namespace = "Kesomannen"
name = "FastStartup"
versionNumber = "0.2.0"
description = "Skip the menus and get right into the action!"
websiteUrl = "https://github.com/Kesomannen/RepoFastStartup"

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Hamunii-AutoHookGenPatcher = "1.0.6"

[build]
icon = "./assets/icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/netstandard2.1/FastStartup.dll"
target = "FastStartup.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
communities = ["repo"]

[publish.categories]
repo = ["tools"]
